Feature: Tone determination of the syllable

  Scenario Outline: Determine the lexical tone of the syllable
    When I look up the lexical tone of the syllable <syllable>
    Then I should expect the tone <tone>
    Examples:
      | syllable | tone         |
      | เดิม     | MID_TONE     |
      | เตียง    | MID_TONE     |
      | ปืน      | MID_TONE     |
      | กวาด     | LOW_TONE     |
      | เกลียด   | LOW_TONE     |
      | จูบ      | LOW_TONE     |
      | อา       | MID_TONE     |
      | ยุ       | HIGH_TONE    |
      | ตา       | MID_TONE     |
      | ตี       | MID_TONE     |
      | อาย      | MID_TONE     |
      | กิน      | MID_TONE     |
      | จริง     | MID_TONE     |
      | เต็ม     | MID_TONE     |
      | เด็ก     | LOW_TONE     |
      | จัด      | LOW_TONE     |
      | เจ็บ     | LOW_TONE     |
      | เป็ด     | LOW_TONE     |
      | ปริ      | LOW_TONE     |
      | จะ       | LOW_TONE     |
      | หา       | RISING_TONE  |
      | ผี       | RISING_TONE  |
      | หนู      | RISING_TONE  |
      | เผาะ     | LOW_TONE     |
      | แฉะ      | LOW_TONE     |
      | มา       | MID_TONE     |
      | ชาน      | MID_TONE     |
      | งู       | MID_TONE     |
      | มาก      | FALLING_TONE |
      | ภาค      | FALLING_TONE |
      | มีด      | FALLING_TONE |
      | ไว       | MID_TONE     |
      | ค        | HIGH_TONE    |
      | ณะ       | HIGH_TONE    |
      | ชิด      | HIGH_TONE    |
      | กล่อง    | LOW_TONE     |
      | กี่      | LOW_TONE     |
      | กลิ่น    | LOW_TONE     |
      | ว่าย     | FALLING_TONE |
      | นี่      | FALLING_TONE |
      | ค่ะ      | FALLING_TONE |
      | ส่าย     | LOW_TONE     |
      | ถ่าน     | LOW_TONE     |
      | สิ่ง     | LOW_TONE     |
      | กุ้ง     | FALLING_TONE |
      | ตั้ง     | FALLING_TONE |
      | อึ้บ     | FALLING_TONE |
      | เก้า     | FALLING_TONE |
      | ใกล้     | FALLING_TONE |
      | ได้      | FALLING_TONE |
      | กล้อง    | FALLING_TONE |
      | ห้าม     | FALLING_TONE |
      | ร้าน     | HIGH_TONE    |
      | ช้า      | HIGH_TONE    |
      | ลิ้น     | HIGH_TONE    |
      | แบ๊งค์   | HIGH_TONE    |
      | ก๊วน     | HIGH_TONE    |
      | ตุ๊ก     | HIGH_TONE    |
      | ปั๊ม     | HIGH_TONE    |
      | อิ๊ว     | HIGH_TONE    |
      | โก๋      | RISING_TONE  |
      | ตี๋      | RISING_TONE  |
      | พ่อ      | FALLING_TONE |